# nested stacks allow you you to isolate repeated patterns / common components in separate stacks and call them from other stacks 
# e.g load balancer or security groups that is re-used, to update them, always use the parent (root stack) 
# if the resources can be dedicated to one stack only & must be re-usable pieces pf code then use nested stacks


Parameters:
  VPCId:
    Description: VPC to create the security group and EC2 instance into
    Type: AWS::EC2::VPC::Id

# mappings that can be applied in any region you want for any ami that works for you
Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-6869aa05
    us-west-2:
      HVM64: ami-7172b611
    us-west-1:
      HVM64: ami-31490d51
    eu-west-1:
      HVM64: ami-f9dd458a
    eu-central-1:
      HVM64: ami-ea26ce85
    ap-northeast-1:
      HVM64: ami-374db956
    ap-northeast-2:
      HVM64: ami-2b408b45
    ap-southeast-1:
      HVM64: ami-a59b49c6
    ap-southeast-2:
      HVM64: ami-dc361ebf
    ap-south-1:
      HVM64: ami-ffbdd790
    us-east-2:
      HVM64: ami-f6035893
    sa-east-1:
      HVM64: ami-6dd04501
    cn-north-1:
      HVM64: ami-8e6aa0e3

Resources:

  # nested stack 
  SSHSecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      # URL for your s3 bucket (created manually)
      TemplateURL: https://s3.amazonaws.com/cloudformation-bucket-common-mycorp/ssh-security-group.yaml
      Parameters:
        ApplicationName: !Ref AWS::StackName
        # vpc_id at the beginning of the code referenced here 
        VPCId: !Ref VPCId
      # how long do i wait for the stack to be created before i say there is a failure in mins
      TimeoutInMinutes: 5


  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      
      # Note we use the pseudo parameter AWS::Region
      # use image_id from mapping defined above 
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', HVM64]
      
      # this is my region the a is for us-east1-a
      AvailabilityZone: !Sub ${AWS::Region}a
      SecurityGroupIds:
      
        # get the attribute from SSHSecurityGroupStack above , refenrencing the output and SSHGroupId
        - !GetAtt SSHSecurityGroupStack.Outputs.SSHGroupId


